// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTicketUseds(t *testing.T) {
	t.Parallel()

	query := TicketUseds()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTicketUsedsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTicketUsedsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TicketUseds().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTicketUsedsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TicketUsedSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTicketUsedsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TicketUsedExists(ctx, tx, o.TicketID, o.UsedBy)
	if err != nil {
		t.Errorf("Unable to check if TicketUsed exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TicketUsedExists to return true, but got false.")
	}
}

func testTicketUsedsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	ticketUsedFound, err := FindTicketUsed(ctx, tx, o.TicketID, o.UsedBy)
	if err != nil {
		t.Error(err)
	}

	if ticketUsedFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTicketUsedsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TicketUseds().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTicketUsedsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TicketUseds().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTicketUsedsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	ticketUsedOne := &TicketUsed{}
	ticketUsedTwo := &TicketUsed{}
	if err = randomize.Struct(seed, ticketUsedOne, ticketUsedDBTypes, false, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}
	if err = randomize.Struct(seed, ticketUsedTwo, ticketUsedDBTypes, false, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = ticketUsedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = ticketUsedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TicketUseds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTicketUsedsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	ticketUsedOne := &TicketUsed{}
	ticketUsedTwo := &TicketUsed{}
	if err = randomize.Struct(seed, ticketUsedOne, ticketUsedDBTypes, false, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}
	if err = randomize.Struct(seed, ticketUsedTwo, ticketUsedDBTypes, false, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = ticketUsedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = ticketUsedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func ticketUsedBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func ticketUsedAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TicketUsed) error {
	*o = TicketUsed{}
	return nil
}

func testTicketUsedsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TicketUsed{}
	o := &TicketUsed{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TicketUsed object: %s", err)
	}

	AddTicketUsedHook(boil.BeforeInsertHook, ticketUsedBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	ticketUsedBeforeInsertHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.AfterInsertHook, ticketUsedAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	ticketUsedAfterInsertHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.AfterSelectHook, ticketUsedAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	ticketUsedAfterSelectHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.BeforeUpdateHook, ticketUsedBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	ticketUsedBeforeUpdateHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.AfterUpdateHook, ticketUsedAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	ticketUsedAfterUpdateHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.BeforeDeleteHook, ticketUsedBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	ticketUsedBeforeDeleteHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.AfterDeleteHook, ticketUsedAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	ticketUsedAfterDeleteHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.BeforeUpsertHook, ticketUsedBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	ticketUsedBeforeUpsertHooks = []TicketUsedHook{}

	AddTicketUsedHook(boil.AfterUpsertHook, ticketUsedAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	ticketUsedAfterUpsertHooks = []TicketUsedHook{}
}

func testTicketUsedsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTicketUsedsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(ticketUsedColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTicketUsedToOneTicketUsingTicket(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TicketUsed
	var foreign Ticket

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, ticketUsedDBTypes, false, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, ticketDBTypes, false, ticketColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Ticket struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TicketID = foreign.TicketID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Ticket().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.TicketID != foreign.TicketID {
		t.Errorf("want: %v, got %v", foreign.TicketID, check.TicketID)
	}

	ranAfterSelectHook := false
	AddTicketHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Ticket) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TicketUsedSlice{&local}
	if err = local.L.LoadTicket(ctx, tx, false, (*[]*TicketUsed)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Ticket == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Ticket = nil
	if err = local.L.LoadTicket(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Ticket == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTicketUsedToOneUserUsingUsedByUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TicketUsed
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, ticketUsedDBTypes, false, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UsedBy = foreign.UserID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UsedByUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.UserID != foreign.UserID {
		t.Errorf("want: %v, got %v", foreign.UserID, check.UserID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TicketUsedSlice{&local}
	if err = local.L.LoadUsedByUser(ctx, tx, false, (*[]*TicketUsed)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UsedByUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UsedByUser = nil
	if err = local.L.LoadUsedByUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UsedByUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTicketUsedToOneSetOpTicketUsingTicket(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TicketUsed
	var b, c Ticket

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, ticketUsedDBTypes, false, strmangle.SetComplement(ticketUsedPrimaryKeyColumns, ticketUsedColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, ticketDBTypes, false, strmangle.SetComplement(ticketPrimaryKeyColumns, ticketColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, ticketDBTypes, false, strmangle.SetComplement(ticketPrimaryKeyColumns, ticketColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Ticket{&b, &c} {
		err = a.SetTicket(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Ticket != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TicketUseds[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TicketID != x.TicketID {
			t.Error("foreign key was wrong value", a.TicketID)
		}

		if exists, err := TicketUsedExists(ctx, tx, a.TicketID, a.UsedBy); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}
func testTicketUsedToOneSetOpUserUsingUsedByUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TicketUsed
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, ticketUsedDBTypes, false, strmangle.SetComplement(ticketUsedPrimaryKeyColumns, ticketUsedColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUsedByUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UsedByUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UsedByTicketUseds[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UsedBy != x.UserID {
			t.Error("foreign key was wrong value", a.UsedBy)
		}

		if exists, err := TicketUsedExists(ctx, tx, a.TicketID, a.UsedBy); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testTicketUsedsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTicketUsedsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TicketUsedSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTicketUsedsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TicketUseds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	ticketUsedDBTypes = map[string]string{`TicketID`: `int`, `UsedBy`: `int`, `UsedDate`: `datetime`}
	_                 = bytes.MinRead
)

func testTicketUsedsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(ticketUsedPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(ticketUsedAllColumns) == len(ticketUsedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTicketUsedsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(ticketUsedAllColumns) == len(ticketUsedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TicketUsed{}
	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, ticketUsedDBTypes, true, ticketUsedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(ticketUsedAllColumns, ticketUsedPrimaryKeyColumns) {
		fields = ticketUsedAllColumns
	} else {
		fields = strmangle.SetComplement(
			ticketUsedAllColumns,
			ticketUsedPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TicketUsedSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTicketUsedsUpsert(t *testing.T) {
	t.Parallel()

	if len(ticketUsedAllColumns) == len(ticketUsedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLTicketUsedUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TicketUsed{}
	if err = randomize.Struct(seed, &o, ticketUsedDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TicketUsed: %s", err)
	}

	count, err := TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, ticketUsedDBTypes, false, ticketUsedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TicketUsed struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TicketUsed: %s", err)
	}

	count, err = TicketUseds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
