// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAgreements(t *testing.T) {
	t.Parallel()

	query := Agreements()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAgreementsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAgreementsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Agreements().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAgreementsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AgreementSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAgreementsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AgreementExists(ctx, tx, o.AgreementID)
	if err != nil {
		t.Errorf("Unable to check if Agreement exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AgreementExists to return true, but got false.")
	}
}

func testAgreementsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	agreementFound, err := FindAgreement(ctx, tx, o.AgreementID)
	if err != nil {
		t.Error(err)
	}

	if agreementFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAgreementsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Agreements().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAgreementsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Agreements().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAgreementsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	agreementOne := &Agreement{}
	agreementTwo := &Agreement{}
	if err = randomize.Struct(seed, agreementOne, agreementDBTypes, false, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}
	if err = randomize.Struct(seed, agreementTwo, agreementDBTypes, false, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = agreementOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = agreementTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Agreements().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAgreementsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	agreementOne := &Agreement{}
	agreementTwo := &Agreement{}
	if err = randomize.Struct(seed, agreementOne, agreementDBTypes, false, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}
	if err = randomize.Struct(seed, agreementTwo, agreementDBTypes, false, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = agreementOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = agreementTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func agreementBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func agreementAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Agreement) error {
	*o = Agreement{}
	return nil
}

func testAgreementsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Agreement{}
	o := &Agreement{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, agreementDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Agreement object: %s", err)
	}

	AddAgreementHook(boil.BeforeInsertHook, agreementBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	agreementBeforeInsertHooks = []AgreementHook{}

	AddAgreementHook(boil.AfterInsertHook, agreementAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	agreementAfterInsertHooks = []AgreementHook{}

	AddAgreementHook(boil.AfterSelectHook, agreementAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	agreementAfterSelectHooks = []AgreementHook{}

	AddAgreementHook(boil.BeforeUpdateHook, agreementBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	agreementBeforeUpdateHooks = []AgreementHook{}

	AddAgreementHook(boil.AfterUpdateHook, agreementAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	agreementAfterUpdateHooks = []AgreementHook{}

	AddAgreementHook(boil.BeforeDeleteHook, agreementBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	agreementBeforeDeleteHooks = []AgreementHook{}

	AddAgreementHook(boil.AfterDeleteHook, agreementAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	agreementAfterDeleteHooks = []AgreementHook{}

	AddAgreementHook(boil.BeforeUpsertHook, agreementBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	agreementBeforeUpsertHooks = []AgreementHook{}

	AddAgreementHook(boil.AfterUpsertHook, agreementAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	agreementAfterUpsertHooks = []AgreementHook{}
}

func testAgreementsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAgreementsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(agreementColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAgreementToManyUserAgreements(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Agreement
	var b, c UserAgreement

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, userAgreementDBTypes, false, userAgreementColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userAgreementDBTypes, false, userAgreementColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.AgreementID = a.AgreementID
	c.AgreementID = a.AgreementID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.UserAgreements().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.AgreementID == b.AgreementID {
			bFound = true
		}
		if v.AgreementID == c.AgreementID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := AgreementSlice{&a}
	if err = a.L.LoadUserAgreements(ctx, tx, false, (*[]*Agreement)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.UserAgreements); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.UserAgreements = nil
	if err = a.L.LoadUserAgreements(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.UserAgreements); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testAgreementToManyAddOpUserAgreements(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Agreement
	var b, c, d, e UserAgreement

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, agreementDBTypes, false, strmangle.SetComplement(agreementPrimaryKeyColumns, agreementColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UserAgreement{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userAgreementDBTypes, false, strmangle.SetComplement(userAgreementPrimaryKeyColumns, userAgreementColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*UserAgreement{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddUserAgreements(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.AgreementID != first.AgreementID {
			t.Error("foreign key was wrong value", a.AgreementID, first.AgreementID)
		}
		if a.AgreementID != second.AgreementID {
			t.Error("foreign key was wrong value", a.AgreementID, second.AgreementID)
		}

		if first.R.Agreement != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Agreement != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.UserAgreements[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.UserAgreements[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.UserAgreements().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testAgreementsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAgreementsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AgreementSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAgreementsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Agreements().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	agreementDBTypes = map[string]string{`AgreementID`: `int`, `AgreementCode`: `varchar`, `Summary`: `varchar`, `IsRequired`: `tinyint`, `Priority`: `int`}
	_                = bytes.MinRead
)

func testAgreementsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(agreementPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(agreementAllColumns) == len(agreementPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAgreementsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(agreementAllColumns) == len(agreementPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Agreement{}
	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, agreementDBTypes, true, agreementPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(agreementAllColumns, agreementPrimaryKeyColumns) {
		fields = agreementAllColumns
	} else {
		fields = strmangle.SetComplement(
			agreementAllColumns,
			agreementPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AgreementSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAgreementsUpsert(t *testing.T) {
	t.Parallel()

	if len(agreementAllColumns) == len(agreementPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLAgreementUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Agreement{}
	if err = randomize.Struct(seed, &o, agreementDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Agreement: %s", err)
	}

	count, err := Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, agreementDBTypes, false, agreementPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Agreement struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Agreement: %s", err)
	}

	count, err = Agreements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
